trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseNode@1
    inputs:
      version: '18.x' # Update to the latest Node.js version

  - script: |
      cd $(Build.SourcesDirectory)
      npm install -g @angular/cli
      npm install
    displayName: 'Install Dependencies'

  - script: ng build --prod
    displayName: 'Build Angular Application'

  - task: CopyFiles@2
    inputs:
      contents: 'dist/**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
