trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x' # Specify the Node.js version
            displayName: 'Install Node.js'

          - script: |
              npm install -g @angular/cli
              npm install
            displayName: 'Install Angular CLI and Dependencies'

          - script: |
              ng build --prod
            displayName: 'Build Angular Application'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'dist' # Adjust this path as necessary
              ArtifactName: 'drop'
              publishLocation: 'Container'
            displayName: 'Publish Build Artifacts'
