trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    displayName: 'Set Node.js Version'
    inputs:
      version: '18.x'

  - script: |
      npm cache clean --force
    displayName: 'Clean npm Cache'

  - task: Checkout@1
    displayName: 'Checkout Code'

  - script: |
      ls -al
    displayName: 'List Files in Working Directory'

  - script: |
      if [ -f package-lock.json ]; then
        npm ci || npm install
      else
        npm install
      fi
    displayName: 'Install Node Modules'

  - script: |
      ng build --configuration=production
    displayName: 'Build Angular Application'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      pathToPublish: 'dist/<your-app-name>'
      artifactName: 'angular-build'
      publishLocation: 'Container'
