trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # 1. Checkout Code
  - task: UseNode@1
    displayName: 'Set Node.js Version'
    inputs:
      version: '16.x'  # Use the required Node.js version for your Angular app

  # 2. Install Dependencies
  - script: |
      npm install -g @angular/cli
      npm ci
    displayName: 'Install Node Modules'

  # 3. Run Tests
  - script: |
      npm test
    displayName: 'Run Unit Tests'

  # 4. Build Angular Application
  - script: |
      ng build --configuration=production
    displayName: 'Build Angular Application'

  # 5. Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      pathToPublish: 'dist/Angular'  # Replace <your-app-name> with your Angular app folder name
      artifactName: 'angular-build'
      publishLocation: 'Container'
