trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UseNode@1
            inputs:
              version: '18.x' # Specify the Node.js version
            displayName: 'Install Node.js'

          - script: |
              cd path-to-your-directory-if-needed # Change to your project subdirectory if necessary, otherwise remove this line
              npm install -g @angular/cli
              npm install
            displayName: 'Install Angular CLI and Dependencies'

          - script: |
              cd path-to-your-directory-if-needed # Change to your project subdirectory if necessary, otherwise remove this line
              ng build --prod
            displayName: 'Build Angular Application'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'path-to-your-directory-if-needed/dist' # Adjust this path as necessary
              ArtifactName: 'drop'
              publishLocation: 'Container'
            displayName: 'Publish Build Artifacts'
