trigger:
  - main # Adjust as necessary

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x' # Use the latest Node.js version

  - script: |
      npm install -g @angular/cli
      npm install
    displayName: 'Install Dependencies'

  - script: ng build --prod
    displayName: 'Build Angular Application'

  - task: CopyFiles@2
    inputs:
      contents: 'dist/**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
